const a = [
    {code: "0xD0011", desc: "Refresh token refresh yaparken hata."},
    {code: "0xA0001", desc: "Refresh token bulunamadı"},
    {code: "0xAFDD1", desc: "malicious-entrance | kötü amaçlı girdi"},
    {code: "0xA0011", desc: "Session içinde refresh token bulunamadı"},
    {code: "0xA0008", desc: "Refresh token süresi bitmiş"},
    {code: "0xA0009", desc: "Refresh token ile alakalı bir hata"},
    {code: "0xA0000", desc: "Refres token genel hata"},
    {code: "0xAA00C", desc: "Access token redis üzerinde bulunamadı"},
    {code: "0xAA001", desc: "Access token süresi bitmiş ve refresh token bulunamamış"},
    {code: "0xAA002", desc: "Access token süresi btimiş refresh token rediste yok session kontrolde bulunamadı"},
    {code: "0xAA008", desc: "Access token süresi bitmiş, refresh token süreside bitmiş"},
    {code: "0xAA009", desc: "Access token süresi bitmiş, refresh token ile alakalı bir hata"},
    {code: "0xAA00F", desc: "Access token süresi bitmiş, refresh token dan yenilemede genel hata"},
    {code: "0xAA0F9", desc: "Access token ile alakalı bir hata"},
    {code: "0xAA010", desc: "Access token genel hata"},
    {code: "0xAAA10", desc: "Authorization genel hata"},
    {code: "0xC1", desc: "Multer aşamasında dosya boyutunda aşım"},
    {code: "0xC1A", desc: "Nginx aşamasında dosya boyutunda aşım send-paper 25MB"},
    {code: "0xC1B", desc: "Nginx aşamasında dosya boyutunda aşım genel 500MB"},
    {code: "", desc: ""},
    {code: "", desc: ""},
    {code: "", desc: ""},
    {code: "", desc: ""},
    {code: "", desc: ""},
    {code: "", desc: ""},
    {code: "", desc: ""},
    {code: "", desc: ""},
    {code: "", desc: ""},
    {code: "", desc: ""},
    {code: "", desc: ""},
    {code: "", desc: ""},
    {code: "", desc: ""},
    {code: "", desc: ""},
    {code: "", desc: ""},
    {code: "", desc: ""},
    {code: "", desc: ""},
    {code: "", desc: ""},
    {code: "", desc: ""},
    {code: "", desc: ""},
    {code: "", desc: ""},
    {code: "", desc: ""},
    {code: "", desc: ""},
    {code: "", desc: ""},
    {code: "", desc: ""},
    {code: "", desc: ""},
]